### PR TITLE
Feat: Added Authentication

### PR DESCRIPTION
**Pull request by Shrinkhlarajpoot**
Added Authentication 
-Login
-Logout
-Signup

### CODE REVIEW

**Review by gopalbbharadva — APPROVED** [review]
Bug: APIs for signin and login is not working, it's because you have to remove .env file from .gitignore file. Once you do APIs will work.

On click of add to cart and add to wishlist button on product listing page , not navigating to login or signup page. just check once.

**Comment by pritam-kr** [comment]
Everything looks good. but your login form is not working with the test credential. Once look into it.

**Comment by Shrinkhlarajpoot** [comment]
> Bug: APIs for signin and login is not working, it's because you have to remove .env file from .gitignore file. Once you do APIs will work.
> 
> On click of add to cart and add to wishlist button on product listing page , not navigating to login or signup page. just check once.

Okay let me do ...Thanks

**Comment by Shrinkhlarajpoot** [comment]
> Everything looks good. but your login form is not working with the test credential. Once look into it.

okay thanks for mentioning

**Pull request merged**
